// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyqujznhtsnjhvhqeemm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5cXVqem5odHNuamh2aHFlZW1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMDM4NTEsImV4cCI6MjA2NjU3OTg1MX0.MU82tk7WQqLq_laKZbOUZl1Mr2HgdDbaxgT6UDMDB-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);